/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JImage: typeof import('./src/components/JImage.vue')['default']
    JNavbar: typeof import('./src/components/JNavbar/JNavbar.vue')['default']
    JSearch: typeof import('./src/components/JSearch.vue')['default']
    JTabs: typeof import('./src/components/JTabs.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
