/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    JButton: typeof import('./src/components/JButton/JButton.vue')['default']
    JCell: typeof import('./src/components/JCell/JCell.vue')['default']
    JIcon: typeof import('./src/components/JIcon/JIcon.vue')['default']
    JImage: typeof import('./src/components/JImage/JImage.vue')['default']
    JInput: typeof import('./src/components/JInput/JInput.vue')['default']
    JNavbar: typeof import('./src/components/JNavbar/JNavbar.vue')['default']
    JTabs: typeof import('./src/components/JTabs.vue')['default']
  }
}
